name: kafka_vehicle_location
services:
  vehicleDB:
    image: "mysql:8.0"
    container_name: "vehicleDB"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=test"
    volumes:
        - "./sql/baza.sql:/docker-entrypoint-initdb.d/1.sql"
        - "./sql/:/test/"
  kafkaServer:
    image: "apache/kafka:3.8.1"
    container_name: "kafkaServer"
    ports:
      - "9092:9092"
